# ************************************
# * Alexis Tercero
# * 2024-02-20
# * alexistercero55@gmail.com
# * Train word2vec pipeline
# ************************************
name: Train-Word2vec

on:
  push:
    branches: 
      - 10-research-positional-encoding
  pull_request:
    branches: 
      - main

jobs:
  train_model:
    runs-on: [self-hosted, word2vec]

    steps:
      - uses: actions/checkout@v4
      - name: training 
        shell: bash
        run: ./Development/word2vecTrain/train.sh
